name: $(majorVersion).$(minorVersion)$(Rev:.r)
variables:
- name: majorVersion
  value: 0
- name: minorVersion
  value: 1
- name: BuildConfiguration
  value: Release
resources:
- repo: self
queue:
  name: Default
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: custom
    custom: 'pack '
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --include-symbols --include-source -p:Version=$(Build.BuildNumber) WrapYoutubeDl/WrapYoutubeDl.csproj'
    buildProperties: 'version=$(Build.BuildNumber)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'